### ISSUE TITLE
Is the provisioning doc correct?

### ISSUE THREAD

**Issue by benjamin-bergia** [grafana/open-distro-for-elasticsearch-grafana-datasource#29]
Hi,

I am trying to replace my elasticsearch datasources with this plugin. The plugin is installed correctly and I didn't touch my provisioning files since the config and type seemsto be exactly the same than for ES. Unfortunately the query editor is still the same and it looks like it is not using the plugin.

Shouldn't the `type` in [here](https://github.com/grafana/open-distro-for-elasticsearch-grafana-datasource#configure-the-data-source-with-provisioning) be something different than:
```
datasources:
  - name: elasticsearch-v7-filebeat
    type: elasticsearch
```
?

**Comment by Elfo404** [comment]
Hi @benjamin-bergia 
good catch, the correct value is `type: grafana-es-open-distro-datasource`, we need to update the docs.

could you submit a PR?

thanks for reporting it!

**Comment by benjamin-bergia** [comment]
Ok I will have a look. Quick question: is there other options that are different from the elasticsearch datasource and should be document?

**Comment by Elfo404** [comment]
In the provisioning configuration i think no, the id should be the only thing that changed

**Comment by benjamin-bergia** [comment]
I think I have seen an option to enable/disable ppl somewhere but I can't remember where.

**Comment by Elfo404** [comment]
true! should be `jsonData.pplEnabled` (`boolean`). also missing in docs but available in the DS settings:
![Screenshot 2021-05-28 at 11 17 21](https://user-images.githubusercontent.com/1170767/119969294-48b17d80-bfa6-11eb-9716-75aafb9aba73.png)
